FROM ubuntu:noble AS build

# Put all the tools in /opt/tools
ENV WORKDIR=/opt/tools
WORKDIR ${WORKDIR}
# Add binaries to the PATH
ENV PATH="${WORKDIR}/bin:${PATH}"

############################## GENERAL UTILITIES ##############################
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y && apt install -y \
    locales \
    apt-transport-https \
    ca-certificates \
    build-essential \
    git \
    curl \
    wget \
    unzip \
    libtool \
    autoconf \
    make \
    libssl-dev \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && apt clean
RUN locale-gen en_US.UTF-8
# Update certs
RUN update-ca-certificates

############################## LLVM ##############################
ARG CLANG_VER=19
RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh ${CLANG_VER} && \
    apt install -y clang-format-${CLANG_VER} clang-tidy-${CLANG_VER} clang-tools-${CLANG_VER} \
    clang-${CLANG_VER} clangd-${CLANG_VER} libclang-${CLANG_VER}-dev libclang1-${CLANG_VER} \
    libc++-${CLANG_VER}-dev libc++1-${CLANG_VER} libc++abi1-${CLANG_VER} \
    liblldb-${CLANG_VER} libomp-dev libomp5 lld-${CLANG_VER} lldb-${CLANG_VER} llvm-dev \
    llvm-runtime llvm-${CLANG_VER} python3-clang-${CLANG_VER}
COPY docker/update-alternatives-clang.sh update-alternatives-clang.sh
RUN chmod +x ./update-alternatives-clang.sh  && ./update-alternatives-clang.sh ${CLANG_VER} 100

############################## PYTHON ##############################
ENV PYTHON_VER=3.12
RUN apt update && apt upgrade -y && \
    apt install -y python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean

# Create and enable a virtual environment
RUN python${PYTHON_VER} -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN python -m pip install --upgrade pip setuptools wheel

############################## C++ Build Tools ##############################
RUN python -m pip install cmake==3.31.1 meson==1.6.0 ninja==1.11.1.1 conan==2.10.0

############################## C++ Dependencies ##############################

ENV DEPS_DIR=/opt/deps
RUN mkdir -p ${DEPS_DIR}
WORKDIR ${DEPS_DIR}

############################## CONAN DEPS ##############################
ENV CONAN_HOME=/usr/local/app/conan/home

# Set the workdir to the src directory
ENV WORKDIR=/usr/local/app
WORKDIR ${WORKDIR}